### ISSUE TITLE
"posenet_decoder" for Windows

### ISSUE THREAD

**Issue by baghbidi** [google-coral/libcoral#22]
### Description

Hello.

I have been looking for the DLL version of posenet_decoder for Windows but since I couldn't find it online, I decided to build it using bazel.
Added this section to `coral/pose_estimation/BUILD`
```
cc_binary(
    name = "posenet_decoder.dll",
    srcs = ["posenet_decoder_tflite_plugin.cc"],
    linkopts = [
          "-Wl,@rpath/posenet_decoder.dll",
    ],
    linkshared = 1,
    deps = [
        ":posenet_decoder_op",
        "@org_tensorflow//tensorflow/lite:kernel_api",
        "@org_tensorflow//tensorflow/lite:util",
    ],
)
```
It gives me a DLL file but I cannot load it with `load_delegate` and getting this error:
```
Traceback (most recent call last):
  File ".\coral.py", line 32, in <module>
    posenet_decoder_delegate = load_delegate(posenet_shared_lib)
  File "C:\Python37\lib\site-packages\tflite_runtime\interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "C:\Python37\lib\site-packages\tflite_runtime\interpreter.py", line 93, in __init__      
    ctypes.CFUNCTYPE(None, ctypes.c_char_p)
  File "C:\Python37\lib\ctypes\__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python37\lib\ctypes\__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'tflite_plugin_create_delegate' not found
Exception ignored in: <function Delegate.__del__ at 0x000001BCCA7268B8>
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\tflite_runtime\interpreter.py", line 125, in __del__      
    self._library.tflite_plugin_destroy_delegate.argtypes = [ctypes.c_void_p]
  File "C:\Python37\lib\ctypes\__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python37\lib\ctypes\__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'tflite_plugin_destroy_delegate' not found
```
Any idea how I could solve this issue?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support, Feature Request

### Operating System

Windows 10

### Coral Device

USB Accelerator

### Programming Language

Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @baghbidi can you please share the posenet_shared_lib.dll file here. Thanks!

**Comment by baghbidi** [comment]
@hjonnala, here is the compiled DLL: 
[posenet_decoder.dll.zip](https://github.com/google-coral/libcoral/files/8828262/posenet_decoder.dll.zip)

Thanks!

**Comment by baghbidi** [comment]
@hjonnala Any updates?

**Comment by hjonnala** [comment]
edgetpu rutime 14 does not work on windows. So can you please try with release-frogfish and share the build instructions here: https://github.com/google-coral/libcoral/tags

Thanks!

**Comment by baghbidi** [comment]
Hey @hjonnala. Compiled it with frogfish release and still getting the same error

**Comment by hjonnala** [comment]
Have you compiled it on Windows Machine or MacOS? Can you please share the build instruction steps to reproduce the issue.. Thanks!

**Comment by baghbidi** [comment]
Built it on Windows:
- Switched to `release-frogfish` tag in `libcoral` repo
- Switched to `release-frogfish` tag in `libedgetpu` submodule
- Added the below to `libcoral\coral\posenet\BUILD`:
```
cc_binary(
    name = "posenet_decoder.dll",
    srcs = ["posenet_decoder_tflite_plugin.cc"],
    linkshared = 1,
    deps = [
        ":posenet_decoder_op",
        "@org_tensorflow//tensorflow/lite:kernel_api",
        "@org_tensorflow//tensorflow/lite:util",
    ],
)
```
- and finally built it using this command:
`bazel build coral/posenet:posenet_decoder.dll  --experimental_repo_remote_exec --incompatible_restrict_string_escapes=false`

**Comment by hjonnala** [comment]
I have tried to build posenet decoder on Windows similar to what we did for [MacOS](https://github.com/google-coral/project-bodypix/issues/22#issuecomment-940221257). Unfortunately, I am not able to [build](https://github.com/hjonnala/snippets/blob/main/posenet/windows/log1.txt) it successfully due to incomplete build setup on Windows.

**Comment by baghbidi** [comment]
Looking at the error, seems like you're missing some prerequisites:
`The target you are compiling requires Visual C++ build tools`
You can follow the instructions here:
```
https://docs.bazel.build/versions/main/install-windows.html
https://docs.bazel.build/versions/main/windows.html#build-on-windows
```
I am using Bazel 4.2.1

**Comment by baghbidi** [comment]
@hjonnala any updates?
